export const questionPapersSeed = [
  {
    "id": "qp-001",
    "title": "Mathematics - Approved Test",
    "classId": "class-10a",
    "className": "10",
    "section": "A",
    "subjectId": "sub-math",
    "subjectName": "Mathematics",
    "teacherId": "teach-001",
    "teacherName": "Mr. Rajesh Sharma",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Mathematics\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": {
      "fileName": "sample.pdf",
      "fileType": "application/pdf",
      "uploadedAt": "2026-06-02T05:34:25.033Z"
    },
    "status": "Approved",
    "remarks": "Excellent question distribution. Approved for printing.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-002",
    "title": "Mathematics - Rejected Test",
    "classId": "class-10a",
    "className": "10",
    "section": "A",
    "subjectId": "sub-math",
    "subjectName": "Mathematics",
    "teacherId": "teach-001",
    "teacherName": "Mr. Rajesh Sharma",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Mathematics\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Rejected",
    "remarks": "Missing instructions for Section C. Please re-upload.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-003",
    "title": "Mathematics - Submitted Test",
    "classId": "class-10a",
    "className": "10",
    "section": "A",
    "subjectId": "sub-math",
    "subjectName": "Mathematics",
    "teacherId": "teach-001",
    "teacherName": "Mr. Rajesh Sharma",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Mathematics\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Submitted",
    "remarks": "",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-004",
    "title": "Science - Approved Test",
    "classId": "class-10b",
    "className": "10",
    "section": "B",
    "subjectId": "sub-sci",
    "subjectName": "Science",
    "teacherId": "teach-002",
    "teacherName": "Mrs. Priya Verma",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Science\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": {
      "fileName": "sample.pdf",
      "fileType": "application/pdf",
      "uploadedAt": "2026-06-02T05:34:25.034Z"
    },
    "status": "Approved",
    "remarks": "Excellent question distribution. Approved for printing.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-005",
    "title": "Science - Rejected Test",
    "classId": "class-10b",
    "className": "10",
    "section": "B",
    "subjectId": "sub-sci",
    "subjectName": "Science",
    "teacherId": "teach-002",
    "teacherName": "Mrs. Priya Verma",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Science\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Rejected",
    "remarks": "Missing instructions for Section C. Please re-upload.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-006",
    "title": "Science - Submitted Test",
    "classId": "class-10b",
    "className": "10",
    "section": "B",
    "subjectId": "sub-sci",
    "subjectName": "Science",
    "teacherId": "teach-002",
    "teacherName": "Mrs. Priya Verma",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Science\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Submitted",
    "remarks": "",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-007",
    "title": "English - Approved Test",
    "classId": "class-10c",
    "className": "10",
    "section": "C",
    "subjectId": "sub-eng",
    "subjectName": "English",
    "teacherId": "teach-003",
    "teacherName": "Mr. Amit Kumar",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for English\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": {
      "fileName": "sample.pdf",
      "fileType": "application/pdf",
      "uploadedAt": "2026-06-02T05:34:25.034Z"
    },
    "status": "Approved",
    "remarks": "Excellent question distribution. Approved for printing.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-008",
    "title": "English - Rejected Test",
    "classId": "class-10c",
    "className": "10",
    "section": "C",
    "subjectId": "sub-eng",
    "subjectName": "English",
    "teacherId": "teach-003",
    "teacherName": "Mr. Amit Kumar",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for English\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Rejected",
    "remarks": "Missing instructions for Section C. Please re-upload.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-009",
    "title": "English - Submitted Test",
    "classId": "class-10c",
    "className": "10",
    "section": "C",
    "subjectId": "sub-eng",
    "subjectName": "English",
    "teacherId": "teach-003",
    "teacherName": "Mr. Amit Kumar",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for English\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Submitted",
    "remarks": "",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-010",
    "title": "Social Studies - Approved Test",
    "classId": "class-10d",
    "className": "10",
    "section": "D",
    "subjectId": "sub-sst",
    "subjectName": "Social Studies",
    "teacherId": "teach-004",
    "teacherName": "Mrs. Sunita Gupta",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Social Studies\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": {
      "fileName": "sample.pdf",
      "fileType": "application/pdf",
      "uploadedAt": "2026-06-02T05:34:25.034Z"
    },
    "status": "Approved",
    "remarks": "Excellent question distribution. Approved for printing.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-011",
    "title": "Social Studies - Rejected Test",
    "classId": "class-10d",
    "className": "10",
    "section": "D",
    "subjectId": "sub-sst",
    "subjectName": "Social Studies",
    "teacherId": "teach-004",
    "teacherName": "Mrs. Sunita Gupta",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Social Studies\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Rejected",
    "remarks": "Missing instructions for Section C. Please re-upload.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-012",
    "title": "Social Studies - Submitted Test",
    "classId": "class-10d",
    "className": "10",
    "section": "D",
    "subjectId": "sub-sst",
    "subjectName": "Social Studies",
    "teacherId": "teach-004",
    "teacherName": "Mrs. Sunita Gupta",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Social Studies\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Submitted",
    "remarks": "",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-013",
    "title": "Physics - Approved Test",
    "classId": "class-11a",
    "className": "11",
    "section": "A",
    "subjectId": "sub-phy",
    "subjectName": "Physics",
    "teacherId": "teach-005",
    "teacherName": "Dr. Vikram Singh",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Physics\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": {
      "fileName": "sample.pdf",
      "fileType": "application/pdf",
      "uploadedAt": "2026-06-02T05:34:25.034Z"
    },
    "status": "Approved",
    "remarks": "Excellent question distribution. Approved for printing.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-014",
    "title": "Physics - Rejected Test",
    "classId": "class-11a",
    "className": "11",
    "section": "A",
    "subjectId": "sub-phy",
    "subjectName": "Physics",
    "teacherId": "teach-005",
    "teacherName": "Dr. Vikram Singh",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Physics\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Rejected",
    "remarks": "Missing instructions for Section C. Please re-upload.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-015",
    "title": "Physics - Submitted Test",
    "classId": "class-11a",
    "className": "11",
    "section": "A",
    "subjectId": "sub-phy",
    "subjectName": "Physics",
    "teacherId": "teach-005",
    "teacherName": "Dr. Vikram Singh",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Physics\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Submitted",
    "remarks": "",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-016",
    "title": "Chemistry - Approved Test",
    "classId": "class-11b",
    "className": "11",
    "section": "B",
    "subjectId": "sub-chem",
    "subjectName": "Chemistry",
    "teacherId": "teach-006",
    "teacherName": "Dr. Ananya Patel",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Chemistry\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": {
      "fileName": "sample.pdf",
      "fileType": "application/pdf",
      "uploadedAt": "2026-06-02T05:34:25.034Z"
    },
    "status": "Approved",
    "remarks": "Excellent question distribution. Approved for printing.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-017",
    "title": "Chemistry - Rejected Test",
    "classId": "class-11b",
    "className": "11",
    "section": "B",
    "subjectId": "sub-chem",
    "subjectName": "Chemistry",
    "teacherId": "teach-006",
    "teacherName": "Dr. Ananya Patel",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Chemistry\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Rejected",
    "remarks": "Missing instructions for Section C. Please re-upload.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-018",
    "title": "Chemistry - Submitted Test",
    "classId": "class-11b",
    "className": "11",
    "section": "B",
    "subjectId": "sub-chem",
    "subjectName": "Chemistry",
    "teacherId": "teach-006",
    "teacherName": "Dr. Ananya Patel",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Chemistry\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Submitted",
    "remarks": "",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-019",
    "title": "Accountancy - Approved Test",
    "classId": "class-11c",
    "className": "11",
    "section": "C",
    "subjectId": "sub-acc",
    "subjectName": "Accountancy",
    "teacherId": "teach-007",
    "teacherName": "Mr. Arun Khanna",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Accountancy\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": {
      "fileName": "sample.pdf",
      "fileType": "application/pdf",
      "uploadedAt": "2026-06-02T05:34:25.034Z"
    },
    "status": "Approved",
    "remarks": "Excellent question distribution. Approved for printing.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-020",
    "title": "Accountancy - Rejected Test",
    "classId": "class-11c",
    "className": "11",
    "section": "C",
    "subjectId": "sub-acc",
    "subjectName": "Accountancy",
    "teacherId": "teach-007",
    "teacherName": "Mr. Arun Khanna",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Accountancy\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Rejected",
    "remarks": "Missing instructions for Section C. Please re-upload.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-021",
    "title": "Accountancy - Submitted Test",
    "classId": "class-11c",
    "className": "11",
    "section": "C",
    "subjectId": "sub-acc",
    "subjectName": "Accountancy",
    "teacherId": "teach-007",
    "teacherName": "Mr. Arun Khanna",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Accountancy\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Submitted",
    "remarks": "",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-022",
    "title": "Hindi - Approved Test",
    "classId": "class-10",
    "className": "10",
    "section": "A",
    "subjectId": "sub-hin",
    "subjectName": "Hindi",
    "teacherId": "teach-009",
    "teacherName": "Mrs. Meena Joshi",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Hindi\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": {
      "fileName": "sample.pdf",
      "fileType": "application/pdf",
      "uploadedAt": "2026-06-02T05:34:25.034Z"
    },
    "status": "Approved",
    "remarks": "Excellent question distribution. Approved for printing.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-023",
    "title": "Hindi - Rejected Test",
    "classId": "class-10",
    "className": "10",
    "section": "A",
    "subjectId": "sub-hin",
    "subjectName": "Hindi",
    "teacherId": "teach-009",
    "teacherName": "Mrs. Meena Joshi",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Hindi\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Rejected",
    "remarks": "Missing instructions for Section C. Please re-upload.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-024",
    "title": "Hindi - Submitted Test",
    "classId": "class-10",
    "className": "10",
    "section": "A",
    "subjectId": "sub-hin",
    "subjectName": "Hindi",
    "teacherId": "teach-009",
    "teacherName": "Mrs. Meena Joshi",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Hindi\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Submitted",
    "remarks": "",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-025",
    "title": "Biology - Approved Test",
    "classId": "class-11b",
    "className": "11",
    "section": "B",
    "subjectId": "sub-bio",
    "subjectName": "Biology",
    "teacherId": "teach-010",
    "teacherName": "Dr. Suresh Nair",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Biology\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": {
      "fileName": "sample.pdf",
      "fileType": "application/pdf",
      "uploadedAt": "2026-06-02T05:34:25.034Z"
    },
    "status": "Approved",
    "remarks": "Excellent question distribution. Approved for printing.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-026",
    "title": "Biology - Rejected Test",
    "classId": "class-11b",
    "className": "11",
    "section": "B",
    "subjectId": "sub-bio",
    "subjectName": "Biology",
    "teacherId": "teach-010",
    "teacherName": "Dr. Suresh Nair",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Biology\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Rejected",
    "remarks": "Missing instructions for Section C. Please re-upload.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-027",
    "title": "Biology - Submitted Test",
    "classId": "class-11b",
    "className": "11",
    "section": "B",
    "subjectId": "sub-bio",
    "subjectName": "Biology",
    "teacherId": "teach-010",
    "teacherName": "Dr. Suresh Nair",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Biology\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Submitted",
    "remarks": "",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-028",
    "title": "Economics - Approved Test",
    "classId": "class-11c, 11-d",
    "className": "11",
    "section": "A",
    "subjectId": "sub-eco",
    "subjectName": "Economics",
    "teacherId": "teach-011",
    "teacherName": "Mr. Deepak Chopra",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Economics\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": {
      "fileName": "sample.pdf",
      "fileType": "application/pdf",
      "uploadedAt": "2026-06-02T05:34:25.034Z"
    },
    "status": "Approved",
    "remarks": "Excellent question distribution. Approved for printing.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-029",
    "title": "Economics - Rejected Test",
    "classId": "class-11c, 11-d",
    "className": "11",
    "section": "A",
    "subjectId": "sub-eco",
    "subjectName": "Economics",
    "teacherId": "teach-011",
    "teacherName": "Mr. Deepak Chopra",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Economics\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Rejected",
    "remarks": "Missing instructions for Section C. Please re-upload.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-030",
    "title": "Economics - Submitted Test",
    "classId": "class-11c, 11-d",
    "className": "11",
    "section": "A",
    "subjectId": "sub-eco",
    "subjectName": "Economics",
    "teacherId": "teach-011",
    "teacherName": "Mr. Deepak Chopra",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Economics\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Submitted",
    "remarks": "",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-031",
    "title": "Computer Science - Approved Test",
    "classId": "class-11a, 11-b, 11-c",
    "className": "11",
    "section": "A",
    "subjectId": "sub-cs",
    "subjectName": "Computer Science",
    "teacherId": "teach-012",
    "teacherName": "Mr. Alok Mishra",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Computer Science\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": {
      "fileName": "sample.pdf",
      "fileType": "application/pdf",
      "uploadedAt": "2026-06-02T05:34:25.034Z"
    },
    "status": "Approved",
    "remarks": "Excellent question distribution. Approved for printing.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-032",
    "title": "Computer Science - Rejected Test",
    "classId": "class-11a, 11-b, 11-c",
    "className": "11",
    "section": "A",
    "subjectId": "sub-cs",
    "subjectName": "Computer Science",
    "teacherId": "teach-012",
    "teacherName": "Mr. Alok Mishra",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Computer Science\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Rejected",
    "remarks": "Missing instructions for Section C. Please re-upload.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-033",
    "title": "Computer Science - Submitted Test",
    "classId": "class-11a, 11-b, 11-c",
    "className": "11",
    "section": "A",
    "subjectId": "sub-cs",
    "subjectName": "Computer Science",
    "teacherId": "teach-012",
    "teacherName": "Mr. Alok Mishra",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Computer Science\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Submitted",
    "remarks": "",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-034",
    "title": "History - Approved Test",
    "classId": "class-11d",
    "className": "11",
    "section": "D",
    "subjectId": "sub-his",
    "subjectName": "History",
    "teacherId": "teach-013",
    "teacherName": "Dr. Kavita Menon",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for History\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": {
      "fileName": "sample.pdf",
      "fileType": "application/pdf",
      "uploadedAt": "2026-06-02T05:34:25.034Z"
    },
    "status": "Approved",
    "remarks": "Excellent question distribution. Approved for printing.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-035",
    "title": "History - Rejected Test",
    "classId": "class-11d",
    "className": "11",
    "section": "D",
    "subjectId": "sub-his",
    "subjectName": "History",
    "teacherId": "teach-013",
    "teacherName": "Dr. Kavita Menon",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for History\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Rejected",
    "remarks": "Missing instructions for Section C. Please re-upload.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-036",
    "title": "History - Submitted Test",
    "classId": "class-11d",
    "className": "11",
    "section": "D",
    "subjectId": "sub-his",
    "subjectName": "History",
    "teacherId": "teach-013",
    "teacherName": "Dr. Kavita Menon",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for History\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Submitted",
    "remarks": "",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-037",
    "title": "Political Science - Approved Test",
    "classId": "class-11d",
    "className": "11",
    "section": "D",
    "subjectId": "sub-pol",
    "subjectName": "Political Science",
    "teacherId": "teach-014",
    "teacherName": "Mr. Farhan Qureshi",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Political Science\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": {
      "fileName": "sample.pdf",
      "fileType": "application/pdf",
      "uploadedAt": "2026-06-02T05:34:25.034Z"
    },
    "status": "Approved",
    "remarks": "Excellent question distribution. Approved for printing.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-038",
    "title": "Political Science - Rejected Test",
    "classId": "class-11d",
    "className": "11",
    "section": "D",
    "subjectId": "sub-pol",
    "subjectName": "Political Science",
    "teacherId": "teach-014",
    "teacherName": "Mr. Farhan Qureshi",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Political Science\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Rejected",
    "remarks": "Missing instructions for Section C. Please re-upload.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-039",
    "title": "Political Science - Submitted Test",
    "classId": "class-11d",
    "className": "11",
    "section": "D",
    "subjectId": "sub-pol",
    "subjectName": "Political Science",
    "teacherId": "teach-014",
    "teacherName": "Mr. Farhan Qureshi",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Political Science\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Submitted",
    "remarks": "",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-040",
    "title": "Geography - Approved Test",
    "classId": "class-11d",
    "className": "11",
    "section": "D",
    "subjectId": "sub-geo",
    "subjectName": "Geography",
    "teacherId": "teach-015",
    "teacherName": "Mrs. Leela Krishnan",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Geography\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": {
      "fileName": "sample.pdf",
      "fileType": "application/pdf",
      "uploadedAt": "2026-06-02T05:34:25.034Z"
    },
    "status": "Approved",
    "remarks": "Excellent question distribution. Approved for printing.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-041",
    "title": "Geography - Rejected Test",
    "classId": "class-11d",
    "className": "11",
    "section": "D",
    "subjectId": "sub-geo",
    "subjectName": "Geography",
    "teacherId": "teach-015",
    "teacherName": "Mrs. Leela Krishnan",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Geography\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Rejected",
    "remarks": "Missing instructions for Section C. Please re-upload.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-042",
    "title": "Geography - Submitted Test",
    "classId": "class-11d",
    "className": "11",
    "section": "D",
    "subjectId": "sub-geo",
    "subjectName": "Geography",
    "teacherId": "teach-015",
    "teacherName": "Mrs. Leela Krishnan",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Geography\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Submitted",
    "remarks": "",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-043",
    "title": "Business Studies - Approved Test",
    "classId": "class-11c",
    "className": "11",
    "section": "C",
    "subjectId": "sub-bst",
    "subjectName": "Business Studies",
    "teacherId": "teach-016",
    "teacherName": "Mr. Sanjay Malhotra",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Business Studies\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": {
      "fileName": "sample.pdf",
      "fileType": "application/pdf",
      "uploadedAt": "2026-06-02T05:34:25.034Z"
    },
    "status": "Approved",
    "remarks": "Excellent question distribution. Approved for printing.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-044",
    "title": "Business Studies - Rejected Test",
    "classId": "class-11c",
    "className": "11",
    "section": "C",
    "subjectId": "sub-bst",
    "subjectName": "Business Studies",
    "teacherId": "teach-016",
    "teacherName": "Mr. Sanjay Malhotra",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Business Studies\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Rejected",
    "remarks": "Missing instructions for Section C. Please re-upload.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-045",
    "title": "Business Studies - Submitted Test",
    "classId": "class-11c",
    "className": "11",
    "section": "C",
    "subjectId": "sub-bst",
    "subjectName": "Business Studies",
    "teacherId": "teach-016",
    "teacherName": "Mr. Sanjay Malhotra",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Business Studies\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Submitted",
    "remarks": "",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-046",
    "title": "Physical Education - Approved Test",
    "classId": "class-10a",
    "className": "10",
    "section": "A",
    "subjectId": "act-games",
    "subjectName": "Physical Education",
    "teacherId": "teach-017",
    "teacherName": "Mr. Ramesh Iyer",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Physical Education\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": {
      "fileName": "sample.pdf",
      "fileType": "application/pdf",
      "uploadedAt": "2026-06-02T05:34:25.034Z"
    },
    "status": "Approved",
    "remarks": "Excellent question distribution. Approved for printing.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-047",
    "title": "Physical Education - Rejected Test",
    "classId": "class-10a",
    "className": "10",
    "section": "A",
    "subjectId": "act-games",
    "subjectName": "Physical Education",
    "teacherId": "teach-017",
    "teacherName": "Mr. Ramesh Iyer",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Physical Education\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Rejected",
    "remarks": "Missing instructions for Section C. Please re-upload.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-048",
    "title": "Physical Education - Submitted Test",
    "classId": "class-10a",
    "className": "10",
    "section": "A",
    "subjectId": "act-games",
    "subjectName": "Physical Education",
    "teacherId": "teach-017",
    "teacherName": "Mr. Ramesh Iyer",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Physical Education\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Submitted",
    "remarks": "",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-049",
    "title": "Art & Music - Approved Test",
    "classId": "class-10a",
    "className": "10",
    "section": "A",
    "subjectId": "act-art",
    "subjectName": "Art & Music",
    "teacherId": "teach-018",
    "teacherName": "Mrs. Padma Desai",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Art & Music\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": {
      "fileName": "sample.pdf",
      "fileType": "application/pdf",
      "uploadedAt": "2026-06-02T05:34:25.034Z"
    },
    "status": "Approved",
    "remarks": "Excellent question distribution. Approved for printing.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-050",
    "title": "Art & Music - Rejected Test",
    "classId": "class-10a",
    "className": "10",
    "section": "A",
    "subjectId": "act-art",
    "subjectName": "Art & Music",
    "teacherId": "teach-018",
    "teacherName": "Mrs. Padma Desai",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Art & Music\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Rejected",
    "remarks": "Missing instructions for Section C. Please re-upload.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-051",
    "title": "Art & Music - Submitted Test",
    "classId": "class-10a",
    "className": "10",
    "section": "A",
    "subjectId": "act-art",
    "subjectName": "Art & Music",
    "teacherId": "teach-018",
    "teacherName": "Mrs. Padma Desai",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Art & Music\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Submitted",
    "remarks": "",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-052",
    "title": "Library - Approved Test",
    "classId": "class-10a",
    "className": "10",
    "section": "A",
    "subjectId": "act-library",
    "subjectName": "Library",
    "teacherId": "teach-019",
    "teacherName": "Mr. Rohan Sharma",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Library\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": {
      "fileName": "sample.pdf",
      "fileType": "application/pdf",
      "uploadedAt": "2026-06-02T05:34:25.034Z"
    },
    "status": "Approved",
    "remarks": "Excellent question distribution. Approved for printing.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-053",
    "title": "Library - Rejected Test",
    "classId": "class-10a",
    "className": "10",
    "section": "A",
    "subjectId": "act-library",
    "subjectName": "Library",
    "teacherId": "teach-019",
    "teacherName": "Mr. Rohan Sharma",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Library\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Rejected",
    "remarks": "Missing instructions for Section C. Please re-upload.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-054",
    "title": "Library - Submitted Test",
    "classId": "class-10a",
    "className": "10",
    "section": "A",
    "subjectId": "act-library",
    "subjectName": "Library",
    "teacherId": "teach-019",
    "teacherName": "Mr. Rohan Sharma",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Library\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Submitted",
    "remarks": "",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-055",
    "title": "Informatics Practices - Approved Test",
    "classId": "class-11c",
    "className": "11",
    "section": "C",
    "subjectId": "sub-ip",
    "subjectName": "Informatics Practices",
    "teacherId": "teach-020",
    "teacherName": "Mrs. Sneha Patil",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Informatics Practices\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": {
      "fileName": "sample.pdf",
      "fileType": "application/pdf",
      "uploadedAt": "2026-06-02T05:34:25.034Z"
    },
    "status": "Approved",
    "remarks": "Excellent question distribution. Approved for printing.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-056",
    "title": "Informatics Practices - Rejected Test",
    "classId": "class-11c",
    "className": "11",
    "section": "C",
    "subjectId": "sub-ip",
    "subjectName": "Informatics Practices",
    "teacherId": "teach-020",
    "teacherName": "Mrs. Sneha Patil",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Informatics Practices\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Rejected",
    "remarks": "Missing instructions for Section C. Please re-upload.",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  },
  {
    "id": "qp-057",
    "title": "Informatics Practices - Submitted Test",
    "classId": "class-11c",
    "className": "11",
    "section": "C",
    "subjectId": "sub-ip",
    "subjectName": "Informatics Practices",
    "teacherId": "teach-020",
    "teacherName": "Mrs. Sneha Patil",
    "examType": "Monthly Test",
    "maxMarks": 50,
    "duration": "2 Hours",
    "content": "Sample content for Informatics Practices\nQ1. Example question 1?\nQ2. Example question 2?",
    "uploadedFile": null,
    "status": "Submitted",
    "remarks": "",
    "createdAt": "2026-06-02T05:34:25.034Z",
    "updatedAt": "2026-06-02T05:34:25.034Z"
  }
];
