import { ROLES } from "./roles";

/**
 * Enterprise navigation mapping by role.
 */
export const ROLE_NAVIGATION = {
  [ROLES.STUDENT]: [
    { id: "home", icon: "LayoutDashboard" },
    { id: "assignments", icon: "ClipboardEdit" },
    { id: "courses", icon: "BookOpen" },
    { id: "timetable", icon: "CalendarClock" },
    { id: "examination", icon: "BookCheck" },
    { id: "academicResults", icon: "Award" },
    { id: "feeDetails", icon: "WalletCards" },
    { id: "transport", icon: "Bus" },
    { id: "clubsCommittees", icon: "Palette" },
    { id: "mentorSupport", icon: "HeartHandshake" },
    { id: "documents", icon: "FolderOpen" },
    { id: "achievements", icon: "Trophy" },
    { id: "student_duty", icon: "BadgeCheck" },
    { id: "calendar", icon: "CalendarDays" },
    { id: "leave", icon: "Palmtree" },
    { id: "support_center", icon: "LifeBuoy" },
    { id: "withdrawal_request", icon: "FileMinus" },
    { id: "profile", icon: "UserCircle" },
    { id: "logout", icon: "LogOut" },
  ],
  [ROLES.PARENT]: [
    { id: "home", icon: "LayoutDashboard" },
    { id: "assignments", icon: "ClipboardEdit" },
    { id: "courses", icon: "BookOpen" },
    { id: "timetable", icon: "CalendarClock" },
    { id: "examination", icon: "BookCheck" },
    { id: "academicResults", icon: "Award" },
    { id: "feeDetails", icon: "WalletCards" },
    { id: "transport", icon: "Bus" },
    { id: "mentorSupport", icon: "HeartHandshake" },
    { id: "documents", icon: "FolderOpen" },
    { id: "achievements", icon: "Trophy" },
    { id: "clubsCommittees", icon: "Palette" },
    { id: "duty_records", icon: "BadgeCheck" },
    { id: "calendar", icon: "CalendarDays" },
    { id: "leave", icon: "Palmtree" },
    { id: "support_center", icon: "LifeBuoy" },
    { id: "withdrawal_request", icon: "FileMinus" },
    { id: "profile", icon: "UserCircle" },
    { id: "logout", icon: "LogOut" },
  ],
  [ROLES.TEACHER]: [
    { id: "teacher_home", icon: "LayoutDashboard" },
    { id: "teacher_leaves", icon: "Palmtree" },
    { id: "teacher_my_attendance", icon: "UserCheck" },
    { id: "attendance_mgmt", icon: "CheckSquare" },
    { id: "assignments_mgmt", icon: "ClipboardEdit" },
    { id: "teacher_examinations", icon: "BookCheck" },
    { id: "teacher_question_papers", icon: "FileQuestion" },
    { id: "teacher_academic_results", icon: "Award" },
    { id: "class_timetable", icon: "CalendarClock" },
    { id: "student_perf", icon: "LineChart" },
    { id: "class_updates", icon: "Megaphone" },
    { id: "student_duty", icon: "BadgeCheck" },
    { id: "mentorship_mgmt", icon: "HeartHandshake" },
    { id: "clubs_activities", icon: "Palette" },
    { id: "calendar", icon: "CalendarDays" },
    { id: "support_center", icon: "LifeBuoy" },
    { id: "teacher_exit_tracking", icon: "FileMinus" },
    { id: "profile_settings", icon: "UserCircle" },
    { id: "logout", icon: "LogOut" },
  ],
  [ROLES.ADMIN]: [
    { id: "admin_home", icon: "LayoutDashboard" },
    { id: "admin_students", icon: "Users" },
    { id: "admin_teachers", icon: "Presentation" },
    { id: "admin_employees", icon: "UserCog" },
    { id: "admin_parents", icon: "HeartHandshake" },
    { id: "admin_student_exit", icon: "FileMinus" },
    { id: "admin_classes", icon: "School" },
    { id: "admin_subjects", icon: "BookOpen" },
    { id: "admin_timetable", icon: "CalendarClock" },
    { id: "admin_exams", icon: "BookCheck" },
    { id: "admin_assessment_governance", icon: "Scale" },
    { id: "admin_report_cards", icon: "Award" },
    { id: "admin_question_papers", icon: "FileQuestion" },
    { id: "admin_academic_performance", icon: "LineChart" },
    { id: "admin_attendance", icon: "CheckSquare" },
    { id: "admin_staff_attendance", icon: "Users" },
    { id: "admin_my_attendance", icon: "UserCheck" },
    { id: "admin_leave_management", icon: "CalendarRange" },
    { id: "admin_transport", icon: "Bus" },
    { id: "admin_fees", icon: "WalletCards" },
    { id: "admin_documents", icon: "FolderOpen" },
    { id: "student_duty", icon: "BadgeCheck" },
    { id: "admin_clubs", icon: "Tent" },
    { id: "admin_achievements", icon: "Trophy" },
    { id: "admin_calendar", icon: "CalendarDays" },
    { id: "calendar", icon: "CalendarDays" },
    { id: "admin_notices", icon: "Megaphone" },
    { id: "admin_institutional_planning", icon: "Target" },
    { id: "admin_manage_departments", icon: "Layers" },
    { id: "admin_communication_center", icon: "Send" },
    { id: "admin_support_management", icon: "Headset" },
    { id: "support_center", icon: "LifeBuoy" },
    { id: "admin_employee_leaves", icon: "Palmtree" },
    { id: "admin_profile", icon: "UserCircle" },
    { id: "admin_access_control", icon: "ShieldCheck" },
    { id: "admin_school_settings", icon: "Settings" },
    { id: "logout", icon: "LogOut" },
  ],
};

/**
 * Structured sections for the Admin Portal sidebar.
 */
export const ADMIN_SECTIONS = [
  {
    title: "Dashboard",
    items: [{ id: "admin_home", icon: "LayoutDashboard", label: "Home" }],
  },
  {
    title: "User Management",
    items: [
      { id: "admin_students", icon: "Users", label: "Students" },
      { id: "admin_teachers", icon: "Presentation", label: "Teachers" },
      { id: "admin_employees", icon: "UserCog", label: "Staff Registry" },
      { id: "admin_parents", icon: "HeartHandshake", label: "Parents" },
      { id: "admin_student_exit", icon: "FileMinus", label: "Student Exit Management" },
    ],
  },
  {
    title: "Academic Management",
    items: [
      { id: "admin_classes", icon: "School", label: "Classes & Sections" },
      { id: "admin_subjects", icon: "BookOpen", label: "Subjects" },
      { id: "admin_timetable", icon: "CalendarClock", label: "Timetable" },
      { id: "admin_exams", icon: "BookCheck", label: "Examination Management" },
      { id: "admin_assessment_governance", icon: "Scale", label: "Assessment Governance" },
      { id: "admin_report_cards", icon: "Award", label: "Academic Report Cards" },
      { id: "admin_question_papers", icon: "FileQuestion", label: "Question Paper Management" },
      { id: "admin_academic_performance", icon: "LineChart", label: "Academic Performance" },
    ],
  },
  {
    title: "Operations",
    items: [
      { id: "admin_attendance", icon: "CheckSquare", label: "Attendance Overview" },
      { id: "admin_staff_attendance", icon: "Users", label: "Staff Attendance" },
      { id: "admin_leave_management", icon: "CalendarRange", label: "Leave Management" },
      { id: "admin_transport", icon: "Bus", label: "Transport" },
      { id: "admin_fees", icon: "WalletCards", label: "Fee Management" },
      { id: "admin_documents", icon: "FolderOpen", label: "Documents" },
      { id: "student_duty", icon: "BadgeCheck", label: "Student Duty Management" },
    ],
  },
  {
    title: "Institutional Activities",
    items: [
      { id: "admin_achievements", icon: "Trophy", label: "Achievements" },
      { id: "admin_calendar", icon: "CalendarDays", label: "Calendar Management" },
      { id: "admin_notices", icon: "Megaphone", label: "Notice Management" },
    ],
  },
  {
    title: "Analytics",
    items: [{ id: "admin_analytics_workload", icon: "PieChart", label: "Teacher Workload" }],
  },
  {
    title: "Institutional",
    items: [
      { id: "admin_institutional_planning", icon: "LayoutDashboard", label: "Institutional Planning" },
      { id: "admin_clubs", icon: "Tent", label: "Club Management Center" },
      { id: "admin_manage_departments", icon: "Layers", label: "Manage Departments" },
      { id: "admin_communication_center", icon: "Send", label: "Communication Center" },
      { id: "admin_support_management", icon: "Headset", label: "Support Management" },
    ],
  },
  {
    title: "Settings",
    items: [
      { id: "admin_access_control", icon: "ShieldCheck", label: "Administrative Controls" },
      { id: "admin_school_settings", icon: "Settings", label: "School Settings" },
    ],
  },
  {
    title: "Personal Workspace",
    items: [
      { id: "admin_profile", icon: "UserCircle", label: "Profile" },
      { id: "admin_my_attendance", icon: "UserCheck", label: "My Attendance" },
      { id: "admin_employee_leaves", icon: "Palmtree", label: "My Leaves" },
      { id: "calendar", icon: "CalendarDays", label: "Academic Calendar" },
      { id: "support_center", icon: "LifeBuoy", label: "Support Center" },
      { id: "logout", icon: "LogOut", label: "Logout" },
    ],
  },
];
