import { ROLES } from "./roles";

/**
 * Enterprise navigation mapping by role.
 */
export const ROLE_NAVIGATION = {
  [ROLES.STUDENT]: [
    { id: "home", icon: "LayoutDashboard" },
    { id: "assignments", icon: "ClipboardEdit" },
    { id: "courses", icon: "BookOpen" },
    { id: "timetable", icon: "CalendarClock" },
    { id: "examination", icon: "BookCheck" },
    { id: "feeDetails", icon: "WalletCards" },
    { id: "transport", icon: "Bus" },
    { id: "clubsCommittees", icon: "Palette" },
    { id: "mentorSupport", icon: "HeartHandshake" },
    { id: "documents", icon: "FolderOpen" },
    { id: "achievements", icon: "Trophy" },
    { id: "student_duty", icon: "BadgeCheck" },
    { id: "calendar", icon: "CalendarDays" },
    { id: "leave", icon: "Palmtree" },
    { id: "support_center", icon: "LifeBuoy" },
    { id: "profile", icon: "UserCircle" },
    { id: "logout", icon: "LogOut" },
  ],
  [ROLES.PARENT]: [
    { id: "home", icon: "LayoutDashboard" },
    { id: "assignments", icon: "ClipboardEdit" },
    { id: "courses", icon: "BookOpen" },
    { id: "timetable", icon: "CalendarClock" },
    { id: "examination", icon: "BookCheck" },
    { id: "feeDetails", icon: "WalletCards" },
    { id: "transport", icon: "Bus" },
    { id: "mentorSupport", icon: "HeartHandshake" },
    { id: "documents", icon: "FolderOpen" },
    { id: "achievements", icon: "Trophy" },
    { id: "clubsCommittees", icon: "Palette" },
    { id: "duty_records", icon: "BadgeCheck" },
    { id: "leave", icon: "Palmtree" },
    { id: "support_center", icon: "LifeBuoy" },
    { id: "profile", icon: "UserCircle" },
    { id: "logout", icon: "LogOut" },
  ],
  [ROLES.TEACHER]: [
    { id: "teacher_home", icon: "LayoutDashboard" },
    { id: "teacher_leaves", icon: "Palmtree" },
    { id: "attendance_mgmt", icon: "CheckSquare" },
    { id: "assignments_mgmt", icon: "ClipboardEdit" },
    { id: "marks_exams", icon: "BookCheck" },
    { id: "question_papers", icon: "FileQuestion" },
    { id: "class_timetable", icon: "CalendarClock" },
    { id: "student_perf", icon: "LineChart" },
    { id: "class_updates", icon: "Megaphone" },
    { id: "student_duty", icon: "BadgeCheck" },
    { id: "mentorship_mgmt", icon: "HeartHandshake" },
    { id: "clubs_activities", icon: "Palette" },
    { id: "leave_mgmt", icon: "CalendarRange" },
    { id: "support_center", icon: "LifeBuoy" },
    { id: "profile_settings", icon: "UserCircle" },
    { id: "logout", icon: "LogOut" },
  ],
  [ROLES.ADMIN]: [
    { id: "admin_home", icon: "LayoutDashboard" },
    { id: "admin_students", icon: "Users" },
    { id: "admin_teachers", icon: "Presentation" },
    { id: "admin_employees", icon: "UserCog" },
    { id: "admin_employee_leaves", icon: "Palmtree" },
    { id: "admin_parents", icon: "HeartHandshake" },
    { id: "admin_admins", icon: "ShieldCheck" },
    { id: "admin_classes", icon: "School" },
    { id: "admin_subjects", icon: "BookOpen" },
    { id: "admin_timetable", icon: "CalendarClock" },
    { id: "admin_exams", icon: "BookCheck" },
    { id: "admin_question_papers", icon: "FileQuestion" },
    { id: "admin_academic_performance", icon: "LineChart" },
    { id: "admin_attendance", icon: "CheckSquare" },
    { id: "admin_leave_approval", icon: "CheckSquare" },
    { id: "admin_transport", icon: "Bus" },
    { id: "admin_fees", icon: "WalletCards" },
    { id: "admin_documents", icon: "FolderOpen" },
    { id: "admin_clubs", icon: "Palette" },
    { id: "admin_achievements", icon: "Trophy" },
    { id: "admin_calendar", icon: "CalendarDays" },
    { id: "admin_notices", icon: "Megaphone" },
    { id: "student_duty", icon: "BadgeCheck" },
    { id: "admin_institutional_planning", icon: "Target" },
    { id: "admin_manage_departments", icon: "Layers" },
    { id: "admin_communication_center", icon: "Send" },
    { id: "admin_leave_portfolio", icon: "Palmtree" },
    { id: "admin_leave_allocations", icon: "CalendarRange" },
    { id: "admin_profile", icon: "UserCircle" },
    { id: "admin_access_control", icon: "ShieldCheck" },
    { id: "admin_school_settings", icon: "Settings" },
    { id: "logout", icon: "LogOut" },
  ],
};

/**
 * Structured sections for the Admin Portal sidebar.
 */
export const ADMIN_SECTIONS = [
  {
    title: "Dashboard",
    items: [{ id: "admin_home", icon: "LayoutDashboard" }],
  },
  {
    title: "User Management",
    items: [
      { id: "admin_students", icon: "Users" },
      { id: "admin_teachers", icon: "Presentation" },
      { id: "admin_employees", icon: "UserCog" },
      { id: "admin_parents", icon: "HeartHandshake" },
    ],
  },
  {
    title: "Academic Management",
    items: [
      { id: "admin_classes", icon: "School" },
      { id: "admin_timetable", icon: "CalendarClock" },
      { id: "admin_exams", icon: "BookCheck" },
      { id: "admin_question_papers", icon: "FileQuestion" },
      { id: "admin_academic_performance", icon: "LineChart" },
    ],
  },
  {
    title: "Operations",
    items: [
      { id: "admin_attendance", icon: "CheckSquare" },
      { id: "admin_leave_management", icon: "CalendarRange" },
      { id: "admin_transport", icon: "Bus" },
      { id: "admin_fees", icon: "WalletCards" },
      { id: "admin_documents", icon: "FolderOpen" },
      { id: "student_duty", icon: "BadgeCheck" },
    ],
  },
  {
    title: "Institutional Activities",
    items: [
      { id: "admin_clubs", icon: "Palette" },
      { id: "admin_achievements", icon: "Trophy" },
      { id: "admin_calendar", icon: "CalendarDays" },
      { id: "admin_notices", icon: "Megaphone" },
    ],
  },
  {
    title: "Analytics",
    items: [{ id: "admin_analytics_workload", icon: "PieChart" }],
  },
  {
    title: "Institutional",
    items: [
      { id: "admin_institutional_planning", icon: "LayoutDashboard" },
      { id: "admin_club_management", icon: "Tent" },
      { id: "admin_manage_departments", icon: "Layers" },
      { id: "admin_communication_center", icon: "Send" },
      { id: "admin_support_management", icon: "Headset" },
      { id: "support_center", icon: "LifeBuoy" },
    ],
  },
  {
    title: "Settings",
    items: [
      { id: "admin_profile", icon: "UserCircle" },
      { id: "admin_employee_leaves", icon: "Palmtree" },
      { id: "admin_access_control", icon: "ShieldCheck" },
      { id: "admin_school_settings", icon: "Settings" },
      { id: "logout", icon: "LogOut" },
    ],
  },
];
